name: Build and Deploy to GKE
on:
  push:
    branches:
      - mail-service

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: product-tracker-cluster    # Add your cluster name here.
  GKE_ZONE: europe-central2   # Add your cluster zone here.
  DEPLOYMENT_NAME: mail # Add your deployment name here.
  IMAGE: ${{ secrets.GCP_APPLICATION }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}/${{ env.DEPLOYMENT_NAME }}:$GITHUB_SHA
        gcloud config set run/region europe-central2
