-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 19:35:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Website` ;

CREATE TABLE IF NOT EXISTS `Website` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `nom` VARCHAR(100) NULL,
  `url` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CountryCode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CountryCode` ;

CREATE TABLE IF NOT EXISTS `CountryCode` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `code` VARCHAR(10) NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seller` ;

CREATE TABLE IF NOT EXISTS `Seller` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `nom` VARCHAR(100) NOT NULL,
  `idCountryCode` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vendeur_CodePays1_idx` (`idCountryCode` ASC),
  CONSTRAINT `fk_Vendeur_CodePays1`
    FOREIGN KEY (`idCountryCode`)
    REFERENCES `CountryCode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `nom` VARCHAR(45) NOT NULL,
  `url` VARCHAR(700) NULL,
  `idWebsite` INT NOT NULL,
  `idSeller` INT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Produit_Site1_idx` (`idWebsite` ASC),
  INDEX `fk_Produit_Vendeur1_idx` (`idSeller` ASC),
  CONSTRAINT `fk_Produit_Site1`
    FOREIGN KEY (`idWebsite`)
    REFERENCES `Website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Vendeur1`
    FOREIGN KEY (`idSeller`)
    REFERENCES `Seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductPrice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductPrice` ;

CREATE TABLE IF NOT EXISTS `ProductPrice` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `price` INT NULL,
  `date` DATETIME NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProduitPrix_Produit_idx` (`idProduct` ASC),
  CONSTRAINT `fk_ProduitPrix_Produit`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserProduct` ;

CREATE TABLE IF NOT EXISTS `UserProduct` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key\n',
  `idProduct` INT NOT NULL,
  `userGUID` VARCHAR(100) NOT NULL,
  `priceLimit` INT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_UserProduct_Product1_idx` (`idProduct` ASC),
  CONSTRAINT `fk_UserProduct_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SellerWebsite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SellerWebsite` ;

CREATE TABLE IF NOT EXISTS `SellerWebsite` (
  `idSeller` INT NOT NULL,
  `idWebsite` INT NOT NULL,
  PRIMARY KEY (`idSeller`, `idWebsite`),
  INDEX `fk_Seller_has_Website_Website1_idx` (`idWebsite` ASC),
  INDEX `fk_Seller_has_Website_Seller1_idx` (`idSeller` ASC),
  CONSTRAINT `fk_Seller_has_Website_Seller1`
    FOREIGN KEY (`idSeller`)
    REFERENCES `Seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seller_has_Website_Website1`
    FOREIGN KEY (`idWebsite`)
    REFERENCES `Website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TypeAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TypeAccount` ;

CREATE TABLE IF NOT EXISTS `TypeAccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(450) NOT NULL,
  `password` VARCHAR(4000) NOT NULL,
  `firstname` VARCHAR(200) NULL,
  `lastname` VARCHAR(200) NULL,
  `GUID` VARCHAR(50) NOT NULL,
  `idTypeAccount` INT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_User_TypeAccount1_idx` (`idTypeAccount` ASC),
  UNIQUE INDEX `GUID_UNIQUE` (`GUID` ASC),
  CONSTRAINT `fk_User_TypeAccount1`
    FOREIGN KEY (`idTypeAccount`)
    REFERENCES `TypeAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
