# This workflow will do a clean install of node dependencies,
# Build the source code
# Run tests across different versions of node

name: Boulanger Crawler CI

on:
  pull_request:
    branches: [prod/boulanger-crawler, dev/boulanger-crawler]

jobs:
  Install-Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
      - name: Run the tests
        run: |
          npm test