name: Back End CI

on:
  push:
    branches: [dev-api]
  pull_request:
    branches: [dev-api]

jobs:
  Install-Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Authentication on app engine
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.BACK_END_CREDENTIALS }}'

      - name: Google App Engine Deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: globetrotteur
          credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
          flags: --no-cache
          deliverables: app.yaml