name: Back End CI

on:
  push:
    branches: [dev-api]

env:
  AUTH_API_URL: https://productracker-zcddpyns6q-lm.a.run.app

jobs:
  Install-Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show where i am
        run: |
          pwd

      - name: Whats inside
        run: |
          ls -a

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
